// Movies
export const FETCH_POPULAR_MOVIES = "FETCH_POPULAR_MOVIES";
export const FETCH_UPCOMING_MOVIES = "FETCH_UPCOMING_MOVIES";
export const FETCH_PLAYING_MOVIES = "FETCH_PLAYING_MOVIES";
export const FETCH_TOPRATED_MOVIES = "FETCH_TOPRATED_MOVIES";
export const FETCH_MOVIE_DETAILS = "FETCH_MOVIE_DETAILS";
export const FETCH_SEARCH_RESULTS = "FETCH_SEARCH_RESULTS";

// TV
export const FETCH_POPULAR_TV = "FETCH_POPULAR_TV"
export const FETCH_UPCOMING_TV = "FETCH_UPCOMING_TV"
export const FETCH_PLAYING_TV = "FETCH_PLAYING_TV"
export const FETCH_TOPRATED_TV = "FETCH_TOPRATED_TV"
export const FETCH_TV_DETAILS = "FETCH_TV_DETAILS"
export const FETCH_SEARCH_RESULTS_TV = "FETCH_SEARCH_RESULTS_TV"

